# SPDX-License-Identifier: WTFNMFPL
# Turns aerials.m3u (made by main.py) into ../src/js/aerials.js so the app can load it
# with a plain <script> tag. Run main.py first, then this, from this folder.
#
# Each entry becomes {"n": name, "s": source, "u": url}, e.g.
#   #EXTINF:-1 group-title="Apple",Apple - East Asia   ->   {"n": "East Asia", "s": "Apple", "u": "https://..."}
import json
import os
import re

here = os.path.dirname(os.path.abspath(__file__))
entries = []
pending = None
with open(os.path.join(here, "aerials.m3u"), encoding="utf-8") as m3u:
    for line in m3u:
        line = line.strip()
        info = re.match(r'#EXTINF:[^ ]* group-title="([^"]*)",(.*)$', line)
        if info:
            source, title = info.group(1), info.group(2)
            prefix = source + " - "
            name = title[len(prefix):] if title.startswith(prefix) else title
            pending = {"n": name.strip(), "s": source}
        elif line.startswith("http"):
            entry = pending or {"n": line.rsplit("/", 1)[-1], "s": "Unknown"}
            entry["u"] = line
            entries.append(entry)
            pending = None

out = os.path.join(here, "..", "src", "js", "aerials.js")
with open(out, "w", encoding="utf-8") as js:
    js.write("// Generated by NetworkVideo/make_js.py from aerials.m3u, do not edit by hand.\n")
    js.write("// n = name, s = source, u = url\n")
    js.write("const aerials=[\n")
    js.write(",\n".join(json.dumps(e, ensure_ascii=False, separators=(",", ":")) for e in entries))
    js.write("\n];\n")

print(f"Wrote {len(entries)} videos to {os.path.normpath(out)}")
