# SPDX-License-Identifier: WTFNMFPL
# Turns aerials.m3u (made by main.py) into ../src/js/aerials.js so the app can load it
# with a plain <script> tag. Run main.py first, then this, from this folder.
import json
import os

here = os.path.dirname(os.path.abspath(__file__))
urls = []
with open(os.path.join(here, "aerials.m3u"), encoding="utf-8") as m3u:
    for line in m3u:
        line = line.strip()
        if line.startswith("http"):
            urls.append(line)

out = os.path.join(here, "..", "src", "js", "aerials.js")
with open(out, "w", encoding="utf-8") as js:
    js.write("// Generated by NetworkVideo/make_js.py from aerials.m3u, do not edit by hand.\n")
    js.write("const aerials=" + json.dumps(urls, indent=0) + ";\n")

print(f"Wrote {len(urls)} urls to {os.path.normpath(out)}")
